org: gauravdhapola
app: aws-ses-forwarder
service: aws-ses-forwarder
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev

functions:
  hello:
    handler: handler.hello

resources:
  - ${file(oss.yml)}
  -  Resources:
       S3Assets:
         Type: AWS::S3::Bucket
         Properties:
           BucketName: gauravdhapolatestbucket

    